// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package data

import ()

type User struct {
	ID           int64
	Fullname     string
	Email        string
	PasswordHash string
}
